# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Aleksei Malyshev
tagline:          'Personal website'
description:      ''
url:              "https://alekseimalyshev.com"
baseurl:          "/"
gh_baseurl:       "/"
social_media_url: "/public/img/icons"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

github_username: exferro
facebook_username: exferro

paginate:         5

github:
  repo:           https://github.com/Exferro/exferro.github.io

plugins:
  - jekyll-paginate
