# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Aleksei Malyshev
tagline:          "Do not shut up (and calculate if you want)"
description:      "Aleksei Malyshev's Personal Website"
url:              "https://alekseimalyshev.com"
baseurl:          "/"
gh_baseurl:       "/"
social_media_url: "/public/img/icons"

author:
  name:           "Aleksei Malyshev"

github_username: exferro
facebook_username: exferro

paginate:         5

collections_dir: my_collections

collections:
  research:
    output: true
  projects:
    output: true
  hobbies:
    output: true
  personal:
    output: true

navigation:
  - text: Home
    url: "/"
  - text: Research
    url: "/research"
  - text: Projects
    url: "/projects"
  - text: Hobbies
    url: "/hobbies"    
  - text: Personal
    url: "/personal"
  - text: Publications
    url: "/list_of_publications"

social_media:
  - url: "https://facebook.com/exferro"
    icon: "fa fa-facebook"
    alt: Facebook
  - url: "https://vk.com/exferro"
    icon: "fa fa-vk"
    alt: VK
  - url: "https://github.com/exferro"
    icon: "fa fa-github"
    alt: GitHub
  - url: "https://linkedin.com/in/exferro"
    icon: "fa fa-linkedin"
    alt: LinkedIn


github:
  repo: https://github.com/Exferro/exferro.github.io
  url: "https://alekseimalyshev.com"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
